ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN EXECUTE IMMEDIATE 'REVOKE EXECUTE ON PASSPORT_APP.PROC_TAO_HO_SO FROM PUBLIC'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

GRANT SELECT ON PASSPORT_APP.APP_USERS TO APP_GUEST;
GRANT EXECUTE ON PASSPORT_APP.PROC_TAO_HO_SO TO ROLE_CD;

UPDATE PASSPORT_APP.APP_USERS
SET PASSWORD_HASH = STANDARD_HASH('123', 'SHA256')
WHERE PASSWORD_HASH = 'hashed_pw';

COMMIT;

EXIT;
