--PDBSYS (không cần chạy nếu chưa tạo policy)
ALTER SESSION SET CONTAINER = FREEPDB1;

NOAUDIT POLICY PASSPORT_DML_AUDIT_POL;
DROP AUDIT POLICY PASSPORT_DML_AUDIT_POL;
DROP VIEW SEC_MGR.VW_AUDIT_GS;
--PDBSYS
--Buoc 1: Tạo policy audit (SYSPDB)
CREATE AUDIT POLICY PASSPORT_DML_AUDIT_POL
ACTIONS INSERT ON PASSPORT_APP.PASSPORT_DATA,
        UPDATE ON PASSPORT_APP.PASSPORT_DATA,
        DELETE ON PASSPORT_APP.PASSPORT_DATA,
        INSERT ON PASSPORT_APP.PASSPORT_REQUEST_HISTORY,
        UPDATE ON PASSPORT_APP.PASSPORT_REQUEST_HISTORY,
        DELETE ON PASSPORT_APP.PASSPORT_REQUEST_HISTORY,
        INSERT ON PASSPORT_APP.RESIDENT_DATA,
        UPDATE ON PASSPORT_APP.RESIDENT_DATA,
        DELETE ON PASSPORT_APP.RESIDENT_DATA;

AUDIT POLICY PASSPORT_DML_AUDIT_POL;
--Buoc 2: Tạo view thuộc schema sec_mgr (SYSPDB)
CREATE OR REPLACE VIEW SEC_MGR.VW_AUDIT_GS AS
SELECT 
    EVENT_TIMESTAMP, 
    DBUSERNAME, 
    ACTION_NAME, 
    OBJECT_SCHEMA, 
    OBJECT_NAME, 
    SQL_TEXT
FROM AUDSYS.UNIFIED_AUDIT_TRAIL
WHERE UNIFIED_AUDIT_POLICIES LIKE '%PASSPORT_DML_AUDIT_POL%';
--Buoc 3: Cấp quyền cho role GS (SYSPDB)
GRANT SELECT ON SEC_MGR.VW_AUDIT_GS TO ROLE_GS;

--LỆNH XEM VIEW (gs_nv01)
ALTER SESSION SET CONTAINER = FREEPDB1;

EXEC DBMS_AUDIT_MGMT.FLUSH_UNIFIED_AUDIT_TRAIL;

SELECT 
    TO_CHAR(EVENT_TIMESTAMP, 'HH24:MI:SS DD/MM') AS THOI_GIAN, 
    DBUSERNAME, 
    ACTION_NAME, 
    OBJECT_NAME, 
    SQL_TEXT
FROM SEC_MGR.VW_AUDIT_GS 
ORDER BY EVENT_TIMESTAMP DESC;

--TESTCASE
--Test01: xt_nv01
ALTER SESSION SET CONTAINER = FREEPDB1;

UPDATE PASSPORT_APP.PASSPORT_DATA SET TRANG_THAI = 'Da xac thuc' WHERE REG_ID = 9;
INSERT INTO PASSPORT_APP.PASSPORT_REQUEST_HISTORY (REG_ID, TRANG_THAI_CU, TRANG_THAI_MOI, NGUOI_CAP_NHAT) 
VALUES (9, 'Da nop', 'Da xac thuc', 'xt_nv01');

UPDATE PASSPORT_APP.RESIDENT_DATA SET DIA_CHI_THUONG_TRU = 'Dia chi moi cap nhat' WHERE CCCD = '079203000007';

ROLLBACK;

--Test02: SYS
ALTER SESSION SET CONTAINER = FREEPDB1;

INSERT INTO PASSPORT_APP.RESIDENT_DATA (CCCD, HO_TEN, NGAY_SINH, GIOI_TINH, DIA_CHI_THUONG_TRU, MAC_LABEL) 
VALUES ('999999999999', 'Fake User', SYSDATE, 'Nam', 'Dia chi ao', CHAR_TO_LABEL('PASSPORT_MAC_POL', 'CONF:XT:TW'));

DELETE FROM PASSPORT_APP.RESIDENT_DATA WHERE CCCD = '999999999999';

UPDATE PASSPORT_APP.PASSPORT_REQUEST_HISTORY SET NGUOI_CAP_NHAT = 'Hacker' WHERE REG_ID = 7 AND TRANG_THAI_MOI = 'Da xac thuc';
DELETE FROM PASSPORT_APP.PASSPORT_REQUEST_HISTORY WHERE REG_ID = 7 AND TRANG_THAI_MOI = 'Da xac thuc';

DELETE FROM PASSPORT_APP.PASSPORT_DATA WHERE REG_ID = 7;

ROLLBACK;
--Test03: xd_nv01
SELECT * FROM PASSPORT_APP.PASSPORT_DATA;