ALTER SESSION SET CONTAINER = FREEPDB1;
-- Buoc 1: Khoi tao level, compartment va group
EXEC SA_SYSDBA.CREATE_POLICY(policy_name => 'PASSPORT_MAC_POL', column_name => 'MAC_LABEL');

EXEC SA_COMPONENTS.CREATE_LEVEL('PASSPORT_MAC_POL', 100, 'PUB', 'PUBLIC');
EXEC SA_COMPONENTS.CREATE_LEVEL('PASSPORT_MAC_POL', 200, 'CONF', 'CONFIDENTIAL');
EXEC SA_COMPONENTS.CREATE_LEVEL('PASSPORT_MAC_POL', 300, 'SEC', 'SECRET');

EXEC SA_COMPONENTS.CREATE_COMPARTMENT('PASSPORT_MAC_POL', 10, 'XT', 'XAC_THUC');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('PASSPORT_MAC_POL', 20, 'XD', 'XET_DUYET');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('PASSPORT_MAC_POL', 30, 'LT', 'LUU_TRU');

EXEC SA_COMPONENTS.CREATE_GROUP('PASSPORT_MAC_POL', 100, 'TW', 'TRUNG_UONG', NULL);

--Buoc 2: Dinh nghia nhan hop le, ap dung chinh sach, cap quyen gan nhan cho sec_mgr
EXEC SA_LABEL_ADMIN.CREATE_LABEL('PASSPORT_MAC_POL', 1001, 'PUB:LT:TW');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('PASSPORT_MAC_POL', 2001, 'CONF:XT:TW');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('PASSPORT_MAC_POL', 2002, 'CONF:XD:TW');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('PASSPORT_MAC_POL', 2003, 'CONF:XT,XD,LT:TW');
EXEC SA_LABEL_ADMIN.CREATE_LABEL('PASSPORT_MAC_POL', 3001, 'SEC:XT,XD,LT:TW');

EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY(policy_name => 'PASSPORT_MAC_POL', schema_name => 'PASSPORT_APP', table_name => 'PASSPORT_DATA', table_options => 'READ_CONTROL, WRITE_CONTROL, LABEL_DEFAULT');
EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY(policy_name => 'PASSPORT_MAC_POL', schema_name => 'PASSPORT_APP', table_name => 'RESIDENT_DATA', table_options => 'READ_CONTROL, WRITE_CONTROL, LABEL_DEFAULT');

GRANT PASSPORT_MAC_POL_DBA TO SEC_MGR;

--Buoc 3: Gan nhan (SEC_MGR)
UPDATE PASSPORT_APP.PASSPORT_DATA 
SET MAC_LABEL = CHAR_TO_LABEL('PASSPORT_MAC_POL', 'CONF:XT:TW') 
WHERE TRANG_THAI = 'Da nop';

UPDATE PASSPORT_APP.PASSPORT_DATA 
SET MAC_LABEL = CHAR_TO_LABEL('PASSPORT_MAC_POL', 'CONF:XD:TW') 
WHERE TRANG_THAI IN ('Da xac thuc', 'Tu choi', 'Da duyet');

UPDATE PASSPORT_APP.PASSPORT_DATA 
SET MAC_LABEL = CHAR_TO_LABEL('PASSPORT_MAC_POL', 'PUB:LT:TW') 
WHERE TRANG_THAI = 'Da luu tru';

UPDATE PASSPORT_APP.RESIDENT_DATA 
SET MAC_LABEL = CHAR_TO_LABEL('PASSPORT_MAC_POL', 'CONF:XT,XD,LT:TW');


